export function renderOrder(direction: string) {
  const directionOders = {
    down: [
      'hair.back',
      'body',
      'weapon',
      'body@chest',
      'body@arm1',
      'body@arm2',
      'body@head',
      'lower',
      'upper',
      'hair',
      'ear',
      'eye',
    ],
    left: [
      'hair.back',
      'body',
      'body@arm1',
      'weapon',
      'body@hands',
      'body@arm2',
      'lower',
      'upper',
      'hair',
      'ear',
      'eye',
    ],
    right: [
      'hair.back',
      'body',
      'body@arm1',
      'weapon',
      'body@hands',
      'body@arm2',
      'lower',
      'upper',
      'hair',
      'ear',
      'eye',
    ],
    up: ['weapon', 'body', 'lower', 'upper', 'hair', 'ear', 'eye'],
  } as { [k: string]: string[] }
  return directionOders[direction]
}
